all_countries_alpha2 = {
    "Afghanistan": "AF",
    "Aland": "AX",
    "Albanien": "AL",
    "Albania": "AL",
    "Algerien": "DZ",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarktis": "AQ",
    "Antarctica": "AQ",
    "Antigua und Barbuda": "AG",
    "Antigua and Barbuda": "AG",
    "Argentinien": "AR",
    "Argentina": "AR",
    "Armenien": "AM",
    "Armenia": "AM",
    "Aruba": "AW",
    "Aserbeidschan": "AZ",
    "Azerbaijan": "AZ",
    "Australien": "AU",
    "Australia": "AU",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesch": "BD",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus (Weissrussland)": "BY",
    "Belarus (Belorussia)": "BY",
    "Belgien": "BE",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bhutan": "BT",
    "Bolivien": "BO",
    "Bolivia": "BO",
    "Bolivien": "BO",
    "Bolivia": "BO",
    "Bosnien und Herzegowina": "BA",
    "Bosnia and Herzegovina": "BA",
    "Botsuana": "BW",
    "Botswana": "BW",
    "Bouvetinsel": "BV",
    "Bouvet Island": "BV",
    "Brasilien": "BR",
    "Brazil": "BR",
    "Brit.Terr.Im Indischen Ozean": "IO",
    "Brit.Terr.in the Indian Ocean": "IO",
    "Brunei Darussalam": "BN",
    "Bulgarien": "BG",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Bonaire, Sint Eustatius and Saba": "BQ",
    "Chile": "CL",
    "Chile": "CL",
    "China": "CN",
    "Cook-Inseln Neuseel.Verwaltung": "CK",
    "Cook Islands New Zealand.administration": "CK",
    "Costa Rica": "CR",
    "Cote D'Ivoire (Elfenbeinkueste)": "CI",
    "Cote D'Ivoire (Ivory Coast)": "CI",
    "Curaçao": "CW",
    "Deutschland": "DE",
    "Germany": "DE",
    "Dominica": "DM",
    "Dominikanische Republik": "DO",
    "Dominican Republic": "DO",
    "Dschibuti": "DJ",
    "Djibouti": "DJ",
    "Dänemark": "DK",
    "Denmark": "DK",
    "Ecuador": "EC",
    "El Salvador": "SV",
    "Eritrea": "ER",
    "Estland": "EE",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Eswatini": "SZ",
    "Faeroeer Inseln Dän.Verwaltung": "FO",
    "Faeroe Islands Danish administration": "FO",
    "Falklandinseln (Malvinen)": "FK",
    "Falkland Islands (Malvinas)": "FK",
    "Fidschi": "FJ",
    "Fiji": "FJ",
    "Finnland": "FI",
    "Finland": "FI",
    "Frankreich": "FR",
    "France": "FR",
    "Franz. Südgebiete": "TF",
    "French. Southern territories": "TF",
    "Französisch Guayana": "GF",
    "French Guiana": "GF",
    "Französisch Polynesien": "PF",
    "French Polynesia": "PF",
    "Gabun": "GA",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgien": "GE",
    "Georgia": "GE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Grenada": "GD",
    "Griechenland": "GR",
    "Greece": "GR",
    "Großbritannien": "GB",
    "Great Britain": "GB",
    "Grönland (Dän.Verwaltung)": "GL",
    "Greenland (Danish administration)": "GL",
    "Guadeloupe (Franz.Verwaltung)": "GP",
    "Guadeloupe (French administration)": "GP",
    "Guam (US-Verwaltung)": "GU",
    "Guam (US administration)": "GU",
    "Guatemala": "GT",
    "Guernsey Insel": "GG",
    "Guernsey Island": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Haiti": "HT",
    "Heard und Mc Donald Inseln (unter Austr.Verw.)": "HM",
    "Heard and Mc Donald Islands (under Austr. administration)": "HM",
    "Honduras": "HN",
    "Hongkong": "HK",
    "Hong Kong": "HK",
    "Indien": "IN",
    "India": "IN",
    "Indonesien": "ID",
    "Indonesia": "ID",
    "Irak": "IQ",
    "Iraq": "IQ",
    "Iran": "IR",
    "Irland": "IE",
    "Ireland": "IE",
    "Island": "IS",
    "Iceland": "IS",
    "Israel": "IL",
    "Italien": "IT",
    "Italy": "IT",
    "Jamaika": "JM",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jemen": "YE",
    "Yemen": "YE",
    "Jersey Insel": "JE",
    "Jersey Island": "JE",
    "Jordanien": "JO",
    "Jordan": "JO",
    "Jungfern-Inseln (Britisch)": "VG",
    "Virgin Islands (British)": "VG",
    "Jungfern-Inseln (USA)": "VI",
    "Virgin Islands (USA)": "VI",
    "Kaimaninseln": "KY",
    "Cayman Islands": "KY",
    "Kambodscha": "KH",
    "Cambodia": "KH",
    "Kamerun": "CM",
    "Cameroon": "CM",
    "Kanada": "CA",
    "Canada": "CA",
    "Kap Verde": "CV",
    "Cape Verde": "CV",
    "Kasachstan": "KZ",
    "Kazakhstan": "KZ",
    "Katar": "QA",
    "Qatar": "QA",
    "Kenia": "KE",
    "Kenya": "KE",
    "Kirgisistan": "KG",
    "Kyrgyzstan": "KG",
    "Kiribati": "KI",
    "Kokosinseln (Keeling)": "CC",
    "Coconut Islands (Keeling)": "CC",
    "Kolumbien": "CO",
    "Colombia": "CO",
    "Kolumbien": "CO",
    "Colombia": "CO",
    "Komoren": "KM",
    "Comoros": "KM",
    "Kongo": "CG",
    "Congo": "CG",
    "Kongo": "CD",
    "Congo": "CD",

    "Kosovo": "XK",
    "Kroatien": "HR",
    "Croatia": "HR",
    "Kuba": "CU",
    "Cuba": "CU",
    "Kuba": "CU",
    "Cuba": "CU",
    "Kuwait": "KW",
    "Laos": "LA",
    "Lesotho": "LS",
    "Lesotho": "LS",
    "Lettland": "LV",
    "Latvia": "LV",
    "Libanon": "LB",
    "Lebanon": "LB",
    "Liberien": "LR",
    "Liberia": "LR",
    "Libysch-Arabische Dschamahirija": "LY",
    "Libyan Arab Jamahiriya": "LY",
    "Liechtenstein": "LI",
    "Litauen": "LT",
    "Lithuania": "LT",
    "Luxemburg": "LU",
    "Luxembourg": "LU",
    "Macao": "MO",
    "Madagaskar": "MG",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Malediven": "MV",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marokko": "MA",
    "Morocco": "MA",
    "Marshall Inseln": "MH",
    "Marshall Islands": "MH",
    "Martinique Franz.Verwaltung": "MQ",
    "Martinique French administration": "MQ",
    "Mauretanien": "MR",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexiko": "MX",
    "Mexico": "MX",
    "Mexiko": "MX",
    "Mexico": "MX",
    "Mikronesien": "FM",
    "Micronesia": "FM",
    "Moldau": "MD",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolei": "MN",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat (GB-Verwaltung)": "MS",
    "Montserrat (GB Administration)": "MS",
    "Mosambik": "MZ",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Neukaledonien": "NC",
    "New Caledonia": "NC",
    "Neuseeland": "NZ",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niederlande": "NL",
    "Netherlands": "NL",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue (Neuseel.Verwaltung)": "NU",
    "Niue (New Zealand.Administration)": "NU",
    "Norfolkinsel": "NF",
    "Norfolk Island": "NF",
    "Norwegen": "NO",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palästina": "PS",
    "Palestine": "PS",
    "Panama": "PA",
    "Panama": "PA",
    "Papua Neuguinea": "PG",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippinen": "PH",
    "Philippines": "PH",
    "Pitcairninsel": "PN",
    "Pitcairn Island": "PN",
    "Polen": "PL",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico (US-Verwaltung)": "PR",
    "Puerto Rico (US administration)": "PR",
    "Republik Nordmazedonien": "MK",
    "Republic of North Macedonia": "MK",
    "Reunion": "RE",
    "Ruanda": "RW",
    "Rwanda": "RW",
    "Rumänien": "RO",
    "Romania": "RO",
    "Russische Föderation": "RU",
    "Russian Federation": "RU",
    "Saint Barthélemy (Franz.Verwaltung)": "BL",
    "Saint Barthélemy (French administration)": "BL",
    "Saint Martin (Franz. Verwaltung)": "MF",
    "Saint Martin (French administration)": "MF",
    "Salomonen": "SB",
    "Solomon Islands": "SB",
    "Sambia": "ZM",
    "Zambia": "ZM",
    "Samoa-Amerikanisch (US-Verwaltung)": "AS",
    "Samoan-American (US administration)": "AS",
    "Samoa-West": "WS",
    "Samoa West": "WS",
    "San Marino": "SM",
    "Sao Tome und Principe": "ST",
    "Sao Tome and Principe": "ST",
    "Saudi-Arabien": "SA",
    "Saudi Arabia": "SA",
    "Schweden": "SE",
    "Sweden": "SE",
    "Schweiz": "CH",
    "Switzerland": "CH",
    "Senegal": "SN",
    "Serbien (exkl. Kosovo)": "RS",
    "Serbia (excl. Kosovo)": "RS",
    "Seychellen": "SC",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Simbabwe": "ZW",
    "Zimbabwe": "ZW",
    "Singapur": "SG",
    "Singapore": "SG",
    "Slowakei": "SK",
    "Slovakia": "SK",
    "Slowenien": "SI",
    "Slovenia": "SI",
    "Somalia": "SO",
    "Spanien": "ES",
    "Spain": "ES",
    "Spitzb. und Jan Mayen Insel (Norw.Verw.)": "SJ",
    "Spitzb. and Jan Mayen Island (Norw.Verw.)": "SJ",
    "Sri Lanka": "LK",
    "St. Martin": "SX",
    "St. Vincent und die Grenadinen": "VC",
    "St. Vincent and the Grenadines": "VC",
    "St.Helena": "SH",
    "St.Kitts und Nevis": "KN",
    "St.Kitts and Nevis": "KN",
    "St.Lucia": "LC",
    "St.Pierre und Miquelon": "PM",
    "St.Pierre and Miquelon": "PM",
    "Sudan": "SD",
    "Suriname": "SR",
    "Syrien": "SY",
    "Syria": "SY",
    "Südafrika": "ZA",
    "South Africa": "ZA",
    "Südgeorgien und Süd-Sandwich-Insel": "GS",
    "South Georgia and South Sandwich Island": "GS",
    "Südsudan": "SS",
    "South Sudan": "SS",
    "Tadschikistan": "TJ",
    "Tajikistan": "TJ",
    "Taiwan": "TW",
    "Tansania": "TZ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau (Neuseel.Verwaltung)": "TK",
    "Tokelau (New Zealand administration)": "TK",
    "Tonga": "TO",
    "Trinidad und Tobago": "TT",
    "Trinidad and Tobago": "TT",
    "Tschad": "TD",
    "Chad": "TD",
    "Tschechien": "CZ",
    "Czech Republic": "CZ",
    "Tunesien": "TN",
    "Tunisia": "TN",
    "Turkmenistan": "TM",
    "Turks- und Caicosinseln": "TC",
    "Turks and Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Türkei": "TR",
    "Turkey": "TR",
    "USA - Sonstige Kleine Inseln": "UM",
    "USA - Other Small Islands": "UM",
    "USA - Vereinigte Staaten": "US",
    "USA - United States": "US",
    "Uganda": "UG",
    "Ukraine": "UA",
    "Ungarn": "HU",
    "Hungary": "HU",
    "Uruguay": "UY",
    "Uruguay": "UY",
    "Uruguay": "UY",
    "Usbekistan": "UZ",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatikan": "VA",
    "Vatican": "VA",
    "Venezuela": "VE",
    "Vereinigte Arabische Emirate": "AE",
    "United Arab Emirates": "AE",
    "Vietnam": "VN",
    "Wallis und Futuna": "WF",
    "Wallis and Futuna": "WF",
    "Weihnachtsinsel (Austr.Verwaltung)": "CX",
    "Christmas Island (Austr.administration)": "CX",
    "Westsahara Eigenst.Staat": "EH",
    "Western Sahara Proprietary state": "EH",
    "Westsahara Eigenst.Staat": "EH",
    "Western Sahara Proprietary state": "EH",
    "Zentralafrikanische Republik": "CF",
    "Central African Republic": "CF",
    "Zypern": "CY",
    "Cyprus": "CY",
    "Ägypten": "EG",
    "Egypt": "EG",
    "Äquatorial Guinea": "GQ",
    "Equatorial Guinea": "GQ",
    "Äthiopien": "ET",
    "Ethiopia": "ET",
    "Österreich": "AT",
    "Austria": "AT",

    "Belarus" : "BY", 
    "Brunei" : "BN",
    "Cabo Verde" : "CV",
    "Congo (Congo-Brazzaville)" : "CG",        
    "Czechia (Czech Republic)" : "CZ",
    "Democratic Republic of the Congo" : "CD", 
    "Eswatini (fmr. Swaziland)" : "SZ",        
    "Holy See" : "VA",
    "Korea (North)" : "KP",
    "Korea (South)" : "KR",
    "Libya" : "LY",
    "Myanmar (Burma)" : "MM",
    "North Macedonia" : "MK",
    "Palestine State" : "PS",
    "Russia" : "RU",
    "Saint Kitts and Nevis" : "KN",
    "Saint Lucia" : "LC",
    "Saint Vincent and the Grenadines" : "VC", 
    "Samoa" : "WS",
    "Serbia" : "RS",
    "United Kingdom" : "GB",
    "United States of America" : "US",
    "vereinigte arabische emirate" : "AE",
    "vereinigtes königreich" : "GB",
    "vereinigte staaten" : "US",
    "österreich" : "AT",
    "schweiz" : "CH",
    "spanien" : "ES",
    "niederlande" : "NL",
    "dänemark" : "DK",
    "schweden" : "SE",
    "norwegen" : "NO",
    "finnland" : "FI",
    "polen" : "PL",
    "ungarn" : "HU",
    "tschechien" : "CZ",
    "griechenland" : "GR",
    "russland" : "RU",
    "ägypten" : "EG",
    "indien" : "IN",
    "turkeye" : "TR",
    "türkiye" : "TR",
    "amerika" : "US",
    "usa" : "US",
    "u.s.a." : "US",
    "england" : "GB",
    "uk" : "GB",
    "u.k." : "GB",
    "deutschland" : "DE",
    "alemania" : "DE",
    "japon" : "JP",
    "nippon" : "JP",
    "espana" : "ES",
    "españa" : "ES",
    "suomi" : "FI",
    "italia" : "IT",
    "ellada" : "GR",
    "elada" : "GR",
    "corea" : "KR",
    "korai" : "KR",
    "rossiya" : "RU",
    "rossiya federatsiya" : "RU",
    "al-mamlakah al-‘arabīyah as-su‘ūdīyah" : "SA",
    "saudi" : "SA",
    "königreich saudi-arabien" : "SA",
    "al-arabīyah as-saʻūdīyah" : "SA",
    "misr" : "EG",
    "masr" : "EG",
    "al-qahira" : "EG",
    "bharat" : "IN",
    "hindustan" : "IN",
    "bharath" : "IN",
    "zhongguo" : "CN",
    "zhonghua" : "CN",
    "sverige" : "SE",
    "danmark" : "DK",
    "norge" : "NO",
    "al-jazair" : "DZ",
    "dzayer" : "DZ",
    "maghreb" : "MA",
    "maghrib" : "MA",
    "al-maghrib" : "MA",
    "ivory coast" : "CI",
    "cote d'ivoire" : "CI",
    "côte d'ivoire" : "CI",
    "kambodja" : "KH", 
    "kampuchea" : "KH",
    "viet nam" : "VN",
    "slovensko" : "SK",
    "slovak republik" : "SK",
    "cesko" : "CZ",
    "ceska" : "CZ",
    "czechia" : "CZ",
    "iran" : "IR",
    "iranian" : "IR",
    "persia" : "IR", 
    "uae" : "AE",
    "u.a.e." : "AE",
    "emirates" : "AE",
    "al-imarat" : "AE",
    "al-emarat" : "AE",
    "frankreich" : "FR",
    "italien" : "IT",
    
    "Åland" : "AX",
    "Amerikanisch-Samoa" : "AS",
    "Antigua/Barbuda" : "AG",
    "Äquatorialguinea" : "GQ",
    "Aserbaidschan" : "AZ",
    "Bosnien/Herzegowina" : "BA",
    "Cookinseln" : "CK",
    "Elfenbeinküste" : "CI",
    "Falklandinseln" : "FK",
    "Französisch-Guayana" : "GF",
    "Französisch-Polynesien" : "PF",
    "Französische Südpolarterritorien" : "TF",
    "Färöer" : "FO",
    "Grönland" : "GL",
    "Guadeloupe" : "GP",
    "Guam" : "GU",
    "Guernsey" : "GG",
    "Heard und McDonaldinseln" : "HM",
    "Isle Of Man" : "IM",
    "Jersey" : "JE",
    "Jungferninseln, Amerikanische" : "VI",
    "Jungferninseln, Britische" : "VG",
    "Kokosinseln" : "CC",
    "Libyen" : "LY",
    "Maldiven" : "MV",
    "Marshallinseln" : "MH",
    "Martinique" : "MQ",
    "Mazedonien" : "MK",
    "Moldawien" : "MD",
    "Montserrat" : "MS",
    "Morokko" : "MA",
    "Niederländische Antillen" : "AN",
    "Niue" : "NU",
    "Nordkorea" : "KP",
    "Nördliche Marianen" : "MP",
    "Palestina" : "PS",
    "Papua-Neuguinea" : "PG",
    "Pitcairninseln" : "PN",
    "Puerto Rico" : "PR",
    "Russland" : "RU",
    "Réunion" : "RE",
    "Serbien" : "RS",
    "Slowakische Republik" : "SK",
    "St. Barthélemy" : "BL",
    "St. Helena" : "SH",
    "St. Kitts/Nevis" : "KN",
    "St. Lucia" : "LC",
    "St. Pierre/Miquelon" : "PM",
    "St. Vincent/Die Grenadinen" : "VC",
    "Surinam" : "SR",
    "Svalbard/Jan Mayen" : "SJ",
    "Swasiland" : "SZ",
    "São Tomé/Príncipe" : "ST",
    "Südgeorgien/Südlichen Sandwichinseln" : "GS",
    "Südkorea" : "KR",
    "Tokelau" : "TK",
    "Tschechoslowakei" : "CZ",
    "Tunisien" : "TN",
    "United States Minor Islands" : "UM",
    "USA" : "US",
    "Vatikanstadt" : "VA",
    "Wallis/Futuna" : "WF",
    "Weihnachtsinsel" : "CX",
    "Weißrussland" : "BY",
    "Westsahara" : "EH",
}